---
- name: Download mamba.
  ansible.builtin.get_url:
    url: 'https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh'
    dest: /tmp/mamba.sh
    mode: 0744
- name: Install mamba.
  ansible.builtin.command: > 
    /tmp/mamba.sh -b -f -p {{ home_path }}/miniforge3 
  args:
    creates: "{{ home_path }}/miniforge3/bin/mamba"
- name: Add Mamba to PATH environment variable.
  ansible.builtin.lineinfile:
    path: '{{ home_path }}/.bashrc'
    line: 'export PATH={{ home_path }}/miniforge3/bin:$PATH'
    create: yes
    state: present  
- name: Install apt packages.
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg: 
      - build-essential
      - cmake
      - libgsl-dev
      - libhts-dev
      - libjemalloc-dev
      - libz-dev
      - libzstd-dev
      - python3-distutils 
      - python3-setuptools
      - python3-dev
      - pkg-config
      - jellyfish
      - minimap2
      - samtools
- name: Install snakemake.
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - 'snakemake=={{ snakemake_version }}'
    - pulp==2.7.0
- name: Add conda init bash to .bashrc
  ansible.builtin.lineinfile:
    path: '{{ home_path }}/.bashrc'
    line: "{{ home_path }}/miniforge3/bin/conda init bash"
    state: present
    create: yes
  notify:
    - reload bash